data_folder = "corpus"
staging_folder = "corpus/staging"
sources = ["patents", "academic"]

# this section needs to be manually updated
# as new country data is found.  Of course,
# this needs to be done automatically in the future.
countries = [
    ("australia", "oceania"),
    ("austria", "europe"),
    ("belarus", "europe"),
    ("belgium", "europe"),
    ("canada", "northamerica"),
    ("china", "asia"),
    ("cyprus", "europe"),
    ("czechrepublic", "europe"),
    ("denmark", "europe"),
    ("ecuador", "southamerica"),
    ("finland", "europe"),
    ("france", "europe"),
    ("ghana", "africa"),
    ("germany", "europe"),
    ("greece", "europe"),
    ("india", "asia"),
    ("iraq", "asia"),
    ("israel", "mideast"),
    ("italy", "europe"),
    ("japan", "asia"),
    ("jordan", "asia"),
    ("liechtenstein", "europe"),
    ("morocco", "africa"),
    ("netherlands", "europe"),
    ("norway", "europe"),
    ("nigeria", "africa"),
    ("pakistan", "asia"),
    ("poland", "europe"),
    ("portugal", "europe"),
    ("romania", "europe"),
    ("russia", "asia"),
    ("saudiarabia", "mideast"),
    ("serbia", "europe"),
    ("singapore", "asia"),
    ("southafrica", "africa"),
    ("southkorea", "asia"),
    ("spain", "europe"),
    ("srilanka", "asia"),
    ("sweden", "europe"),
    ("slovakrepublick", "europe"),
    ("slovenia", "europe"),
    ("switzerland", "europe"),
    ("turkey", "europe"),
    ("taiwan", "asia"),
    ("uae", "mideast"),
    ("uk", "europe"),
    ("ukraine", "europe"),
    ("us", "northamerica"),
]
